apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV5Z0F3SUJBZ0lKQUtSQ2NZZ0ZqOTBFTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweE9URXdNVGN5TWpJME1qbGFGdzAwTnpBek1EUXlNakkwTWpsYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFNTmR0bDhqQlArdzIzT1V2eDcreXMwZ000bFdSQkhObjNTRHI2alFmRXRZN2dGcSt4REMKdHRObXdOeVlnQ2pyVDhRY3d0aVBBbFQyYmhqQXRWMTVnVUk5YVllTkMrSVNWYjhTcUQ1YkhaS0JtWmZhZ0R4RwpFM1NiVzl1S2R4Y1dGYVBOS0xHdXp4ZEttQzNJUnhmUzVZUC9yVk1FSlo1RzdTZ2psSXIzSmRLMVVmSUF5Tkg3CitXSmJkb0drUUhnLytyMG5WeXUwbk5NVHlnN0JhZHZPdWxWUExnL1RjYzZRWkF0d3B1NWNTUFNtazJOOWJUbFgKeGRBSVFMTWdSeVNQY200VzJ3dlV6N282M2lMSzFzWmg4VUFBa05VMjFwWmJJZVkvRHZEbWlxSTZqV3R3dWV0TQpCZUtNMk1UbUdBeks5SWYrcGlZOTVDcmduMXdYMWRCTlhjOENBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGQURDCmJadmJLQXl2dHQ0NXFnaHFMRmpQODFHaE1COEdBMVVkSXdRWU1CYUFGQURDYlp2YktBeXZ0dDQ1cWdocUxGalAKODFHaE1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLYi9rNDV0bVUzSQpFTzgyYTBBVnQyaTJFSGVIOFNvTVIwVnl4SEpXeWM0Z0hDR1RZSkpyNjJkRmU5bUprQmRBay9kU3JQTE8zM2EyClJSNXpDR2F0Z2ZPN3R1eWpsL3lJVEkxb2RiVWpQU3VOcG0zQVZsdjRGMHpZbHpvK0w5ZnQ2YU05T0l5VHdSK08KMVJrcWRlcjVJZmN3c2pHWFhNOGlNN21MN2R6VHQyZHR5MUFqc3U4dWZiYmNIcFk4OWo5TFBqMTQwZDhpQ0pCWQovK3E4SjN1MDNxUFVZWXBuLzhySElDajVRckhGZUd5NHlVeDlDVHZnWTh3YUtYeXhEQThQZ0wzV0RxVXhUVXMzCkZlRjdDbkRzc0dLTGp1b2tQWC9hOVNab1NVQmEwbUVxOHNOOXlCZ2NzZ2hya1RrQUNrYldrbzJoMDFRVzFmeUcKZGY3WXRUV2hpTEU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://172.26.163.235:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: admin
    password: aEcxeTk5OXZ3TDdIMVltQUJyQzliV0tPT1ZYbm55STFLSEl2UXRtV2JHRT0K